'use server';
/**
 * @fileOverview Generates sales reports with LLM-generated insights.
 *
 * - generateSalesReportWithInsights - A function that generates a sales report and accompanying insights.
 * - GenerateSalesReportWithInsightsInput - The input type for the generateSalesReportWithInsights function.
 * - GenerateSalesReportWithInsightsOutput - The return type for the generateSalesReportWithInsights function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateSalesReportWithInsightsInputSchema = z.object({
  salesData: z.string().describe('Sales data, e.g., in CSV format.'),
});
export type GenerateSalesReportWithInsightsInput = z.infer<
  typeof GenerateSalesReportWithInsightsInputSchema
>;

const GenerateSalesReportWithInsightsOutputSchema = z.object({
  report: z.string().describe('The generated sales report.'),
  insights: z.string().describe('Insights generated by the LLM.'),
});
export type GenerateSalesReportWithInsightsOutput = z.infer<
  typeof GenerateSalesReportWithInsightsOutputSchema
>;

export async function generateSalesReportWithInsights(
  input: GenerateSalesReportWithInsightsInput
): Promise<GenerateSalesReportWithInsightsOutput> {
  return generateSalesReportWithInsightsFlow(input);
}

const generateSalesReportPrompt = ai.definePrompt({
  name: 'generateSalesReportPrompt',
  input: {schema: GenerateSalesReportWithInsightsInputSchema},
  output: {schema: GenerateSalesReportWithInsightsOutputSchema},
  prompt: `You are an expert sales analyst. Analyze the following sales data and generate a sales report with insights.

Sales Data:
{{{salesData}}}

Report and Insights (JSON format):
`,
});

const generateSalesReportWithInsightsFlow = ai.defineFlow(
  {
    name: 'generateSalesReportWithInsightsFlow',
    inputSchema: GenerateSalesReportWithInsightsInputSchema,
    outputSchema: GenerateSalesReportWithInsightsOutputSchema,
  },
  async input => {
    const {output} = await generateSalesReportPrompt(input);
    return output!;
  }
);
